// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    configure: function(client, prefix) {
      this.client = client;
      return this.prefix = prefix;
    },
    read: function(key, expire, generate, cb) {
      return client.get(key, function(err, data) {
        if (err != null) {
          return cb(err);
        }
        if (data != null) {
          return cb(JSON.parse(data));
        }
        return generate(function(err, data) {
          if (err != null) {
            return cb(err);
          }
          client.setex("" + prefix + ":" + key, expire, JSON.stringify(data));
          return cb(null, data);
        });
      });
    }
  };

}).call(this);
