// Generated by CoffeeScript 1.4.0
(function() {
  var Cache;

  Cache = (function() {

    function Cache(client, prefix) {
      this.client = client;
      this.prefix = prefix;
    }

    Cache.prototype.read = function(key, expire, generate, cb) {
      var _this = this;
      return this.client.get("" + this.prefix + ":" + key, function(err, data) {
        if (err != null) {
          return cb(err);
        }
        if (data != null) {
          return cb(null, JSON.parse(data));
        }
        return generate(key, function(err, data) {
          if (err != null) {
            return cb(err);
          }
          _this.client.setex("" + _this.prefix + ":" + key, expire, JSON.stringify(data));
          return cb(null, data);
        });
      });
    };

    return Cache;

  })();

  module.exports = Cache;

}).call(this);
